### ISSUE TITLE
[Botbuilder-AI] Remove the @azure-ms-rest dependency

### ISSUE THREAD

**Issue by Bill7zz** [southworkscom/botbuilder-js#58]
## Describe the issue
**Botbuilder-ai** has a pinned version of `@azure/ms-rest` [v1.8.13](https://github.com/southworkscom/botbuilder-js/blob/master/libraries/botbuilder-ai/package.json#L24). This version is being used to create a credential that’s used by the LUIS client. 
Right now, the versions are compatibles, but some time ago we had an issue because the LUIS client upgraded its version of `@azure/ms-rest`, which caused some differences between the interfaces.
To avoid this happening again, we want to eliminate the `@azure/ms-rest` dependency. However, we can’t do this because of the coupling between LUIS client and `@azure/ms-rest`. 

Currently, the [LuisRecognizer](https://github.com/southworkscom/botbuilder-js/blob/master/libraries/botbuilder-ai/src/luisRecognizer.ts) class depends on `@azure-ms-rest` to create a [LUISRuntimeClient](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/cognitiveservices/cognitiveservices-luis-runtime/src/lUISRuntimeClient.ts) object.

```
const creds: msRest.TokenCredentials = new msRest.TokenCredentials(this.application.endpointKey);
const baseUri: string = this.application.endpoint || 'https://westus.api.cognitive.microsoft.com';
this.luisClient = new LuisClient(creds as any, baseUri);
```
This implementation caused build issues. The solution was to cast the credentials as `any` to avoid the build to break.

## Possible solution
- Create a LUIS client manually that does not depend on `@azure/ms-rest`.

**Comment by Aliandi** [comment]
Some feedback:
- I feel like some structure is missing here. Maybe divide the issue by titles: Problem, Possible solution. 
- I would explain how the usage of interfaces would reduce the coupling to ms-rest and how that would be implemented, it's not clear the relation between the problem and the solution.
- The final sentence 'Also, open it for future implementations' is not really clear, I'd like to see more information on this in the issue.

**Comment by Bill7zz** [comment]
Thx for the feedback @Aliandi, 

I will add the structure. 

Regarding the explanation of the interface uses, I'm not sure if we need to add this. due to the main goal if to open a question then we will research how to solve the issue. 

Also, I'll add more context for the final sentence.

**Comment by GasparAcevedoZainSouthworks** [comment]
Some minor feedback:
1. Could you add at the beginning a link to the `@azure/ms-rest` version from the respective _package.json_ file
1. You can re-structure this line:
```
.. LUIS client upgraded his version of @azure/ms-rest causing differences in the interfaces.
```
with something like this:
```
... LUIS client upgraded its version of @azure/ms-rest, which caused some differences between the interfaces,
```
3. Missing `.` here: `...eliminate the @azure/ms-rest dependency however we can’t do this`. Should be like this: `eliminate the @azure/ms-rest dependency. However, we can’t do this...`
4. In this sentence `The solution was to cast the credentials as any`, remark the `any`

**Comment by GasparAcevedoZainSouthworks** [comment]
LGTM. :shipit:

**Comment by Bill7zz** [comment]
Promote to MS #[1071](https://github.com/microsoft/botbuilder-js/issues/1071)
