### ISSUE TITLE
[BF-Connector] Remove @azure/ms-rest-js dependency

### ISSUE THREAD

**Issue by Bill7zz** [southworkscom/botbuilder-js#59]
## Issue description

Initially, the **BotFramework-Connector** library was generated by Autorest using `@azure/ms-rest`. With time the autogenerated files were modified to add new functionalities.
 
The last time we attempted to generate **BotFramework-Connector** with a newer version of Autorest and  `@azure/ms-rest`, there was a sizable delta between the generated code and the old code. So we decided to set the `@azure/ms-rest` version to [1.2.6](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-connector/package.json#L22).

Now, we reached a point in which we cannot add more functionalities without updating the `@azure/ms-rest` version. This is the case of the proxy support, only available on `1.8.x` versions of `@azure/ms-rest` (#XXX)

As depending on autogenerated code reduces the possibility to add more functionalities and also makes a dependency couple implementation, it's necessary to stop depending on the autogenerated code and remove the `@azure/ms-rest` dependency.

## Possible solution

Because the current implementation of the **BotFramework-Connector** is tightly coupled to `@azure/ms-rest`, remove this dependency means to redefine most of the library. 

We suggest:

- Regenerate the **BotFramework-Connector** base client using [OpenApi](https://github.com/OpenAPITools/openapi-generator) which doesn’t use `@azure/ms-rest` to have the base structure of the library. **This code will be generated once, and every change/update will be made manually.**

- Make an assessment of the functionalities added in the current implementation of the library. Then porting that into the newest, adding the proxy support at the time.

**Comment by Aliandi** [comment]
`autogenerate files` -> `autogenerated files`

**Comment by GasparAcevedoZainSouthworks** [comment]
Some feedback:

**_ISSUE related feedback_**:
1. I think that the ISSUE name must include the _remove @azure/ms-rest-js_ dependency, as it's one of the most remarkable things that must be done here. Maybe it could be `[BF-Connector] Remove @azure/ms-rest-js dependency`, as the _regeneration_ of the library is one of the possible solution, not the problem itself.

**_Structure & grammar-related feedback_**:
1. It would be great to have a link to the current code when you mention that `we decided to set the @azure/ms-rest version to 1.6.2`
1. `Which is the case of the proxy support` --> `This` _is the case of the proxy support_
1. `Depending on autogenerated code reduces the... Also, makes a dependency...` --> `As` depending on _autogenerated code reduces the..._`, and` _also makes a dependency..._`,` `It's necessary` _to stop depending on the autogenerated code and remove..._
1. `Make an assessment of the functionalities added in the current implementation of the library then porting that into the newest adding the proxy support at the time.` -> _Make an assessment of the functionalities... of the library_. `Then,` _porting that into the newest_`,` _adding the proxy support at the time._

**Comment by GasparAcevedoZainSouthworks** [comment]
More feedback:

1. `So we decided to set the @azure/ms-rest version to 1.6.2.` --> This mention that we are using the v `1.6.2`, but in the link there is a reference to the v `1.2.6`
1. `... without updating the @azure/ms-rest version. this is the case of the proxy support...` --> _... without updating the @azure/ms-rest version._ `T`_his is the case of the proxy support ..._ (Note the capital _T_)
1. `... to add more functionalities and also makes a dependency couple implementation. It's necessary to stop depending on...` -> _... to add more functionalities and also makes a dependency couple implementation_`,` _it's necessary to stop depending on ..._ (Note the `,` instead of the `.`)

**Comment by GasparAcevedoZainSouthworks** [comment]
LGTM. :shipit:

**Comment by Bill7zz** [comment]
Promoted to MS [#1072](https://github.com/microsoft/botbuilder-js/issues/1072)
